import type { Metadata } from "next"
import { Navbar } from "@/components/Navbar"
import { Footer } from "@/components/Footer"
import { SITE_NAME } from "@/lib/constants"

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `${SITE_NAME} terms of service — rules and guidelines for using our platform.`,
}

export default function TermsPage() {
  return (
    <>
      <Navbar />
      <main className="py-24">
        <div className="mx-auto max-w-3xl px-6">
          <h1 className="text-3xl sm:text-4xl font-bold tracking-tight mb-2">Terms of Service</h1>
          <p className="text-sm text-neutral-400 mb-8">Last updated: July 2026</p>

          <div className="space-y-6 text-neutral-600 text-sm leading-relaxed">
            <Section title="1. Acceptance of Terms">
              <p>By using {SITE_NAME}, you agree to these Terms of Service. If you do not agree, do not use the service.</p>
            </Section>

            <Section title="2. Description of Service">
              <p>{SITE_NAME} provides AI-powered social media content generation. Users can create, preview, and copy posts for various platforms.</p>
            </Section>

            <Section title="3. User Accounts">
              <p>You are responsible for maintaining the confidentiality of your account credentials. You must be at least 13 years old to use this service.</p>
            </Section>

            <Section title="4. Acceptable Use">
              <p>You agree not to: generate illegal, harmful, or misleading content; attempt to bypass usage limits; use the service for spam or harassment; reverse-engineer the platform.</p>
            </Section>

            <Section title="5. AI-Generated Content">
              <p>AI-generated content is provided &ldquo;as is&rdquo; without guarantees of accuracy or appropriateness. You are responsible for reviewing and editing content before publication.</p>
            </Section>

            <Section title="6. Subscriptions & Refunds">
              <p>Paid plans are billed monthly. Refunds are handled on a case-by-case basis. Contact us within 7 days of purchase for refund requests. Crypto payments are non-refundable once confirmed on the blockchain.</p>
            </Section>

            <Section title="7. Limitation of Liability">
              <p>{SITE_NAME} is not liable for any damages arising from the use or inability to use the service, including content generated by AI models.</p>
            </Section>

            <Section title="8. Changes to Terms">
              <p>We may modify these terms at any time. Users will be notified of material changes via email. Continued use after changes constitutes acceptance.</p>
            </Section>
          </div>
        </div>
      </main>
      <Footer />
    </>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg font-semibold text-neutral-900 mb-3">{title}</h2>
      {children}
    </section>
  )
}
